
cc_binary(
    name = "divide",
    srcs = ["divide.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "bipartiteness_test",
    srcs = ["bipartiteness_test.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "fenwick_tree",
    srcs = ["fenwick_tree.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "a_star",
    srcs = ["a_star.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "strongly_connected_components",
    srcs = ["strongly_connected_components.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "binary_tree",
    srcs = ["binary_tree.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "dijkstra",
    srcs = ["dijkstra.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "mo_algorithm",
    srcs = ["mo_algorithm.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "dsu",
    srcs = ["dsu.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "knapsack_with_duplicates",
    srcs = ["knapsack_with_duplicates.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "bubble_sort",
    srcs = ["bubble_sort.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "counting_sort",
    srcs = ["counting_sort.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "knapsack",
    srcs = ["knapsack.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "minimum_spanning_tree",
    srcs = ["minimum_spanning_tree.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "nth_element",
    srcs = ["nth_element.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "partition",
    srcs = ["partition.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "hanoi",
    srcs = ["hanoi.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "binary_heap",
    srcs = ["binary_heap.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "graph_heuristic_painting",
    srcs = ["graph_heuristic_painting.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "combinations",
    srcs = ["combinations.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "quick_sort",
    srcs = ["quick_sort.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "factor",
    srcs = ["factor.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "all_divisors",
    srcs = ["all_divisors.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "edit_distance",
    srcs = ["edit_distance.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "floyd_warshall",
    srcs = ["floyd_warshall.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "lcm",
    srcs = ["lcm.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "lis",
    srcs = ["lis.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "merge_sort",
    srcs = ["merge_sort.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "binary_search_with_duplicates",
    srcs = ["binary_search_with_duplicates.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "graph_topological_sort",
    srcs = ["graph_topological_sort.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "josephus",
    srcs = ["josephus.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "median_of_stream",
    srcs = ["median_of_stream.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "permutations",
    srcs = ["permutations.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "gorner",
    srcs = ["gorner.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "bfs",
    srcs = ["bfs.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "prime_test",
    srcs = ["prime_test.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "ll_reverse",
    srcs = ["ll_reverse.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "lru_cache",
    srcs = ["lru_cache.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "dfs",
    srcs = ["dfs.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "ford_bellman",
    srcs = ["ford_bellman.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "gcd",
    srcs = ["gcd.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "subsets",
    srcs = ["subsets.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "min_recursive",
    srcs = ["min_recursive.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "fast_power",
    srcs = ["fast_power.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "sets_in_tree",
    srcs = ["sets_in_tree.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "eulerian_cycle",
    srcs = ["eulerian_cycle.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "money_exchange",
    srcs = ["money_exchange.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "boyer_moore",
    srcs = ["boyer_moore.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "lcs",
    srcs = ["lcs.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "kadanes",
    srcs = ["kadanes.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "erato",
    srcs = ["erato.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "min_stack",
    srcs = ["min_stack.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "knuth_morris_pratt",
    srcs = ["knuth_morris_pratt.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "3sum",
    srcs = ["3sum.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "sliding_window",
    srcs = ["sliding_window.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "multiply",
    srcs = ["multiply.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "jenkins_hash",
    srcs = ["jenkins_hash.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "sqrt",
    srcs = ["sqrt.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)

cc_binary(
    name = "negative_cycle_detection",
    srcs = ["negative_cycle_detection.cc"],
    copts = [
        "-Werror",
        "-std=c++17",
    ],
)
