---
apiVersion: v2
name: pihole-wrapper
description: "Wrapper chart: pihole"
type: application
version: 0.5.0
appVersion: "2024.07.0"
dependencies:
  - name: pihole
    version: 2.37.0
    repository: "https://mojo2600.github.io/pihole-kubernetes/"
