# yamllint disable rule:line-length
pihole:
    adminPassword: ENC[AES256_GCM,data:fij1HpsLD5lI,iv:m6tMLtdBu0K3a9ADxP/7Yxv0LnncNEqerWiPULrecpY=,tag:4N1l71sJ+ibINnvHXH2pmA==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwS0poU1dhSWwwS2pSOEpX
            VmFSVlhEdlMwZ0NVRWVIQTVBbFJXQUhQRHhnCnRtbXBYeFgybDk2d21PQ3lacmZO
            cThoekNGbVRCdVdndmJYdzA1SkdTWmMKLS0tIDMySjJMM282cXBSWVhXRVdNREgz
            YXNqMHlxWGw3QnFSUGVibmdGMzNKK2sKEcGJyWnEBBukLmAC3CqXiUgszCch/I+w
            eueOo7ODkqMCUrPYdzqqPmxjwevsa/0z+EMwlxY8snh2QGLa1K5rjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T12:06:49Z"
    mac: ENC[AES256_GCM,data:azXi21o8D3WUFBfl99hG4XN0wYj7nVShZLJKEafgTL5ec1f5F6VU7+xWuTLqV2hfqt5A0kc8sQzgiT5/7k5DlmV5SeY+WAYAzWHGISwYRD+wGQk20AcA6EGcgNPcs1CCE+kGGD+Mrz0n1+LNMmznHlnagFW0Ik9OOkd+Z0JVyhQ=,iv:71iqiC2c4/tYiiZ30azxRRIi+iL4BQg8g7+j/MzDWXM=,tag:5Xjt6wRgDpX7E/isNiFQjA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
