# yamllint disable rule:line-length
minio:
  rootUser: admin
  rootPassword: mocksecretpassword
  environment:
    MINIO_IDENTITY_OPENID_CLIENT_SECRET: "bf0ce741dc27a153782a468759e147857ba39f79f0b8582b7ae70fef7195e488"
