---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  releaseName: local-path-provisioner
  targetNamespace: local-path-storage
  storageNamespace: local-path-storage
  interval: 10m
  chart:
    spec:
      chart: ./production/kubernetes/helm-charts/local-path-provisioner-wrapper
      sourceRef:
        kind: GitRepository
        name: gerrit
        namespace: flux-system
