---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik
  - buildbuddy
  - cert-manager
  - docker-registry
  - envoy-gateway
  - gerrit
  - gerrit-operator
  - hedgedoc
  - jupyter-cpp
  - kanboard
  - kube-vip
  - kyverno
  - kyverno-policies
  - kubernetes-event-exporter
  - metrics-server
  - miniflux
  - minio
  - nfs
  - ntfy
  - opengrok
  - pihole
  - postgres-ui
  - postgresql
  - redis
  - zookeeper
  - zooreader
  - zuul
