---
tofu-controller:
  replicaCount: 1
  concurrency: 24
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 96Mi
  caCertValidityDuration: 24h
  certRotationCheckFrequency: 30m
  runner:
    grpc:
      maxMessageSize: 30
