# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:tO6cvwVDMtzc/I3llrKq8akaImHrW/Oz3NHjqBlcRKqiPC67ET25K2MZItuAl82xMbKR8Wataf2YeGOPza/OcaIucSYcC3y86gvQbjTku2Si9mTYiKg3hQieBgwO1Lzj145PmmyulTh+uWGXaJYyi0IfR7m5i0Q=,iv:bN0eKAa6zRoHRjjjLIWK0AGY2RQXEFKz4yIEnrXBVA4=,tag:teVbl2ywP1EszGMfljmEqg==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWjdmYzVWRUtEWlFVTkF3
            bmJrY1BiWXVGS3ZHaTNkWU1ZcDNVS3dnLzJzCkVCUC9Va0VtQUFIS0ZpU1Z1cERz
            bVdPdGEycjBZcmF2R0ZTOTR3UmM0bTAKLS0tIE9JdWFqWGY5d1pkZlR2M0w1UnNT
            QUVPWkNudlROU0gvRFk2Y2xOYVFlRGcKspGHoYArbhuI0lPB+GnaloqKL8tuSmic
            dUxVEG2tKIxgRo3og8Hxc2GIL5XPxTqbMLUtOJoXIn/QYy2cnW/xDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T11:22:12Z"
    mac: ENC[AES256_GCM,data:oW0TGQnLEu474UVrVeFfb+RiPTxNZ51P+K7BXwpN7khuYkj7qD7q8Zxau61yCx5UZFP2x4PJdx7/Nmz8p0LGZXDbtwqY6t6KOV9bItv5qikDBRzH2SiGSGAo6DdlayncYLpyvaQzzC7sGjd6ziJjYZ4BbXgdEo1FNv38TShAPv0=,iv:3EHXNzb2vMyjSaIOZAtAZ/p0jTFef28VQYj7e/R6Als=,tag:a2OKUN16LpL4SO8Q9i/lPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
