# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: docker-registry-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:OanSJgrM00yMqLscrtv0aDzu2M2wbQW2xRUwdmRK6LF5mKVyQluEpT22VaSbeW5hP5OJ9IG37djtUWf8rpC0aiSccZL2Ww==,iv:oTyFM/IVsd2DQ/HQf5H0A1+wXrutIMxY/KbgP/7pVs8=,tag:rbIfLpbc8wFnvRx88Axqpw==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUk1XZmd5NmxNL25TZ042
            RlNBZDJmRjZzYzRDU3pNSVVQZ1hqZFdyRzBRCkxzeUplRnE5ek9OQjYwWjI1aXp0
            YXMyNWkwMHA1UmFFKzk0Mzh5bE5Zak0KLS0tIGlaOUZzb3Y1d2diTjhMellDSXJv
            MGZHVlBZMkxjMW96MkFyZTBLdnI2REUK7x97/Wjr6sHXOQ6/T4T5x+7ghrGNNDpX
            mXz9vtN7YULtK4DA7jXLevO1xScXxgarVHBy5AmOKhlJQJo1JU1hsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T17:53:31Z"
    mac: ENC[AES256_GCM,data:38uWmn11fMd+xnDeuLBNCQTRyltVgsHt/BFcKJ+XL7yuJkqfqsJPkQAk+9UC8BcEHmfLgz7OJy+bGlXGbZW6zo2sAn0RJmyXj3EykqXoYUMlXQQh0nOVFIEuMLs8xclMtSpIXWNXEa8HfcQkGttNjGKMRWtqeE0ArqYzM4YjIKo=,iv:RgGHxVCJBOdrHxiNlEdY0EqXmdW+mKWZJ0FVr+Lqoz0=,tag:EO8ieM1rQGOg9gc4RKfWIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
