# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: gerrit-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:6YppiaSiozxbvJVUK7O6I2xhOXlkyzPMyDzTyHpTU/yaBVIU9ihl2hRZErvU4O/nOHV3ll6t8xsqwWfkFUz4r1RffxEL9fjT6e/CadvV25jjEh6DYbJldt1LBMrnVSX25UGjn8JneRMmFVbMdzaskx/gm+bXAXAMeCWfB1xah2Fgj4SFyr/EHrogKd9K6I+Ok2Xb3gIQXFCFBvAa0CPCKRvANA/czLqDj8Z0VVsdgNQOUHAWNqruJwY8lkviRBbxjof/o6GHFc2h14Mal7yHYCFyl2iGmqcAHaVPUZO7PAuutVYFUatQpMBGMIzK6OvhMcV0fsvTypswCylDb71VhybpSofj0iRKZwndJRAzUbtx6odQnDbAMgvd0fiMLntLZvELbRFr61S7YGm5FEeb1kekoUNPSN2ulbHAztPd9d4ivBlxJFo/T0ged84sgtX3eaEk9pWPlJfOUA83ukV6GtttqPPaZgIIXfRREJaOCIyxBeGxNiEgFbXyYGxabTjdGyiNeFf7ANvVVp6tR5vwjUbwrBWO04MpGlkgOZn+VEp6WxmhxWEdD+kU+/ylZqYcaIXI0tDbZLMKS5jUIx1fO3+GbIYWFXgxBwb4ka8jrLiSTHeDjsSN2/ylcb32fmvN/df9VMTqV+H6Xi3DZBnrUKJOjFgO97phODn2UrBvOjPYbxQRJdsvfyWkeOBXI1e3JLv/xfW7Jmp4lEuYcXxxO4T5XBYf8uIRW7vW4dSYmGsDjI8DCR/+95RpG5YNcMEE2avkqQtnLAkmY8iktxqNlyWlA0cThYjgaTaCZ9fhiBxBlWwuLZ3kvNh0eOkpfAEpQgB1bEBkPWBasI877SYOtk9ecGJYlMwjnzt7LKmbBUC3ZEkK/aId8dcTsGZMUnFHnrJ3Ca86juFZT8843pkmxmAZgBmfNdHumfRzO2FbZE0eIZcGc/usGq9J5JQ6bZJz0lX7QZEtj8Hv/gHNmHJGtZUSzrptimEE2qzU/fpMBw3G6kD7LKnmD+hBgsaEhiWVJLc4jeq3ovYA/mZJFTTeQrQifsnS397WlVvlbfu7VyKDUCIkN1wZ1qRCzOQTL6pMjCEBvyIlso+V1rdHtOJWAwhia/3n9a2Hx47RhFcEdvRFZJf16Wydd2QD2BC4IwgyZ9goQd/00g3PDUXcl2Sj4tG828fvtU8TCfCo36H0VaJJ6xO5aI6+Pxpgn5jgythNVID+R3OQUcA3yjyWNpqZdcbxS/tBpaIQBxwxygY38H62q+d6tQ/caq3TfruKBKUlB6bT97Us5rdLQiRGdKFlaAwZ8hoGcvo=,iv:85Qxoh7DAh3yvOYVMCEoGczjKphZ4QJQkwFo96oBZOA=,tag:0EpvOwSJIKFGfcwmkG0GWw==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZWx4aUl6dmpHOFRRZ05h
            MzYySDZaQjMxTHdhMGhHeExGcHlvTTVtWkdvCmZLU3hzYnVlTUtYYUhsTkRFc3Fp
            RkJxUVY0aktYM2VEVDlFVjAzam1mUzgKLS0tIDFlWkJmRm1uVEF4YUFTeWRUVW03
            by9VVG9zTy9GZnBoWHgxSXV4V3RteW8K6niZrv8HeCYvjUSBrVWs5xr5SbnYZlfu
            a0xDpzO19LE1ciKrKGoq25T8EmeWBzRU1ZZ2igrgPTJ0DRhzTgI3fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T17:53:38Z"
    mac: ENC[AES256_GCM,data:Ij4SfuHcKrgHphs9MSufLu+jqUPZ41OOe2gSgR+lRrb1OlytcRnj7Lq0Wsy55X3aZO2SfwANJ7Ods3/B/vzRINOe81QvSiBXfTqhKNKtXbH884HyNEle8xTrLJF0p83IS1MY9CR7aJwl7JQRhcTJn+19RErdiY2lJudQySNHF+k=,iv:eI1UCJGs70rB1/UkRgkwlkYDNVHQ9JEPO2n/F2nG5r4=,tag:LCLw8jJKW+WT3AMLBPOwNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
