# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: hedgedoc-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:g83OyZDKA+zn79+8CsGDb5LBPBjkzliSM2bVpFcOK8tO8I94/i7jXuZVtLnh4KdwqP3ftxqUwLqFwtQbFDmeJR6JX3cArAiYlpSW2rbMoQ9TXj8oX5694LqR/Uw0fsTqa4B6kISXaDrhS6fcxSSiS6v+o44RhegFxksbMm11QguxKjOPCpMcjarHBXGpBpMBAqR+GWsGY7MpLKR95ThO1RysTebJIeG1iSzlVLGJ25mj/AHuQQ2WLe5nTH+OY7xHQjwK3V+dtx2EAX0rnEdMyqnblmmH2zD5jNctpI6uxn8dBVhi9hays91azD82ciWbApWtjRxmKCDzcsnU2PuU6adcjB8KBWuGOhq/h9c+TVanWWKFugHjyXsIRKa5ymKAqg7KTLExBPkFob9cSKHBfVEguZNVBW1O92NdKtP50TCJmpE=,iv:Qn8XF/jJzR+63JXBK3jhSxewXLjUgIEwpKS/dbivB04=,tag:BWogYbyxvbLD3KgLGIJdpA==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUVZmWlRFWDJyOVVIK2Z5
            TTc4L3ZtTWl5RDZkbnNHelp2QXhuVUhzekR3CmprS0NoTG1NU0xIUEJIZHZUc3RD
            U1dQc1g2cVEvZnRYYkdLQ2E3Q1NPNHMKLS0tIGFWcnhRWU11L3MxQUMvS1ZwMHdC
            cTJpTVpJU2M4TXo1d3YxRmdXMGh2VGcKQ8s8VfpprsT9helbLVSnpz8ROC7xk+TQ
            +ldKxK8BozdIqZmtllku5NYuj/a10AzsamHAAGYJeA8eSt6JirN7LA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T11:36:46Z"
    mac: ENC[AES256_GCM,data:bw+gTOLWjcjDlr4I0jkVfrFND3xPbq7ZHwAzf0mpKtqFlQkSnsEVBSlUPwNQDTNLoH3zBv1WImdy+tBMhWfLXX8+mYg69gWVYwFSq0zn1hgPAEtMMktT8uQlLhfCBPJzwoqBtRfBQAZrGpjfABcnJda3G8NtueNy4kiN+upYRug=,iv:RNgQuPKegqmWc3TDube0OsKTZH7IPW+0aB5aDi7UNi4=,tag:c/TMILy6BAAJ+N60Dd5bMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
