# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: minio-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:EVki/+Xoc+kAS/CvFdU9PunD3zRwwWrF2co5hXSEJqV3zg2SdLYkALexGMCCPQWU5k4L6uB8OuefgN1JEjQ1s7hTnwArCcysDOvvD2wuAb6/7TYOPoLKmOGG2U4GkdIWKrougVGEnMwBXgrQ0TKm7PdpiIcn9Pynfhkup8ZjXTZdJPsu27lOdOasdWtSs8vL6b5JwD+A,iv:+hoXR561QGso5n+/c88+DZxP6f3sGMU22GlULCo8v80=,tag:Y9qTHPrFtyqqaXxyCE6uQQ==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcVBXY3NjbVYzRFdyVjZ5
            MDBCbEVjbzdxY3FXWG5SVTBuWE5BOWRmL3lZCkZyNDlmTTJQVnpXd3IvbEpMc2tu
            TUJxMmM4RE9xNjNvUElRUzJZVXZobG8KLS0tIDdJZlBxYW5NdWJ6R1hpYlpETG5i
            V2w3WE9RZUZrZmJGSGhhTm1YbUh1UWMKMz6uf31qDiou8UeGpB/zrACIG3BBusl+
            QvkdSa7mcl1l6K8jxdq+n2vE1G2r1da9sWtnJYl31SQT7TZLZA5eRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T18:41:02Z"
    mac: ENC[AES256_GCM,data:1CgfyX9nU8m1LgOdVZIMCc5ncseKiBXzNgv35K1+ECk1VghvTc8XVaYV7yT5k+Lc4CERamnJStEQgE6DFLMgmo7QlF+tHizNSj3mo/U/gMIqMQMdTi2lslA1AzFUmIKyCSS0vnF+wQaUMwf6q36VmDnnAiPqLvueR6bV4vcYvxA=,iv:fvzle10FNUsTU3C5+xLfelxrY/wpfNmVEgpdgA82NmI=,tag:VtDzsvWFgVRJtSPDU2c+FA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
