# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:21U8Rd+VGJGWzCJjnk48wyO0j2DDoAAGM0F/JG0miRqbpJUrcm0sF1v7sq1wMCsCIKMpQVeOHsd6+pstzm59oDhnFDF4NmCFqg9CoU021dssFDCiCj94ZeIdk8iEJynBTqet8s7nP4ZZHNegVAjc3vHfwlnbuPHeYyPHHZH+IeR0h7c9jTvSyKttyT2wadKGAGwtGG15fOtAsytz2JTnkcMeTyna7LOsJaZkvRryftNkcDWgrXspJgWPMuc5DrfuqgVuXNGNoQPlKA==,iv:YEduDr4EcwNhbYDQ1UlG1cvd5cKfViT5MJfBlJkVKEM=,tag:2oA9rUpSC+Ri7iV4iyUIzA==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZk41VmdKLzkwa3BnVkxh
            YTVwNGY2UEF0ZHRGNTlib3pWOHRhSEpMQ3dvCmlib1lsYkI5ck43L1dDbjFZN0Zs
            eEhrTVZYMmhIVE1FS1VwV2JCN1BEYWcKLS0tIDVwQXpWVG9yM2NXaWFvb01EVjJ5
            YXNEVW9BWlhMamwxbFp0cW5JOW1iZHcKnA3Tg+/Y1CkVL2zAUqAcv9Fa7cUzqwhI
            a6FZl5Ooy9DP7n22nRN4PZ77Kk7zHyuc2Tl7AXlKHJdXvhp5t39FXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T17:54:02Z"
    mac: ENC[AES256_GCM,data:EhNfbqQv9ywh9YdSyH2RjS7YIKbywqqmn8qgI4CpCrqwRmfw9krWYIawFU1/HznG8lav10wRA0U27N8zpGy4xQfx67dTZ+hgP67f/bMv4MMu/OUaTQJ0Fwz8NTZE2qv/OCYDDX4W/lmNcJ3+imhASWmdNBQk0BnVz4Gz2/1Fysg=,iv:f7Q/Cql0t4688Tq43TO2W+e/URNlu4IbvBzjD3DwwTE=,tag:MS1ukFkjMYZhRIHk4Q1UZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
