# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: opengrok-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:F1nAwR0yUWq88j0EONdRKO+84QsQBa1gq3fFpG1w95RN55obd+IkE42JpsGld9HCvAPHClVkUiqJuSOS5rIMeie1+kTepB2k6rhNh4hrEBTA7hju0VqLbXfl4n9DBG/SCP5BU0bajKcvc7xEdPCGEHe1QwPYeUupcqhneEZVe2jh+is08m/Kus/zeUqvu5LVsc/XXl+ioFbq13y7SQ+hm+1rtvFtlXaVxgxLsfrhiIOZmeTvq3mFxaWNpY7Jkhvq/1hzbbEfY/K/DvqP03Zp3HvY7ZnBsSA1KSKt4dDnCOFL7zCJ9z2u7db2mr53Eq7vpR3sqBALCMFgbmD7EVssRsJ0XMCEshjSSxGQ1uvxB9eKsiBkvZgIZJTApLeCXyVJt6Ry9gQWlo4K7EVPGjmMkZKhC3QfScTvLJH2l7OR24knO3cJ+ag0JTZ3ffWDwNpm4ALB4e+pnK/hl/s94PyDXKtysLAjTLK59UEpPlA5b4tWnHdU9QPYi1bwMz9RdAGakfaCePidvzdka69BFxg8vhNoEkGNaEwA9A+1ziUa0WNhtULrZcykeRhacsbInq5gYZCg/vTTMH7YYaya/rRVKyt7iLA7YG8ufEGWXNWMhCE+TSrqWCj5AuRtZOpbxJZ1li6c+f+uLwHt6610gkgEjk657C4ckNGBUv+YysZv/LTybT8fAVMNnw7uRUVXuOr4zFiKViinnPLf/2vh6U/khfwkPpwc8irJhxwW/Kv8MWw76qjarySp4AFDM62pPmvAcX+P28GDx/5JjCsFZuO0o6Zp4h/7d51Vgi51DHYwAcvu2tpn8poZfyxfM/WoerbxcrgXufgM1L+MQ6IkettgUo9je6MifW/SC9v25pG1dLHV5c3RMEaYIbpGQXbqyR/5uKR4k6wUrQ==,iv:8iUAxK6zUY54HnsZw1VV+COQGTK5N5VXMUhhga1FqOE=,tag:SxeMDTicQ1rL/bH8Nmam1w==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OWtXYktqYzdDU2NPaUNZ
            Vk55Q2ROZHM3N1V6OGpZeS8xR3NTR1lhZjNvCjJxK2FUTys3WFlmVmtTclBRbFdw
            RDh3d2VHTXJvVzFhRVQ5aFEwOWx0WDAKLS0tIGZ5aVZVNTdleEJrZzNzOVNxSU5x
            emhFNVNOK1FVNmJLNStaWXR4ZzNiaEUKsfG8BI67GxiS94VIEyJDD4HglhRp0NQ6
            tfy4qc7LyfM6Uk1l06Oy5Xl6BkAuRHn6Xd35PpRGSXB814C8EqD2bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T17:54:09Z"
    mac: ENC[AES256_GCM,data:vlo+KulPNqxe+cBnwazdM9QUF+52V5Q0RHQrsUlChAuS785l/qh8Z/KGmZYPx4cpPhCf4ggWYjIUshkPTwdnt+1Zj79dUTJJ02RSDlq1fZSo5QMD7YILMonZD7jg19mePMauqxGM0E/jPH7inx0NmE/cs099ldrkF3OaaTNUQHk=,iv:MfQazwUCdTyshQQl8y9D+qBcSkuiI4eTbd67mGE22cM=,tag:/ITSnUDMCpRXXwuc/f1B5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
