# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: openai-api
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:RQc22Df476ROVm6kLGcHpFzRbV9j3QhZNfp6VochZ3H3NjWc4lQL3urx2/Dg9nE35tk+G1opPh/WP9eIpAibrPXEPAxpLw7UIV2jYO7GrOj14qs0VGa85ctDZkaUP/iE/T36UogPfw2fsB+yr9wSVIO5LWxfYmZGH85LtzsppPWeURKvRorf4QY6XSrz247LpmxW+EB1Eq7n35L3nSU3NSj5vS3R,iv:qIQyu7mqiCHospVc4MCpbbRH1Zsnfbr04R0jcuX4lEA=,tag:3LzS5tjQsrN4vgEPSEnjPg==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcnFmejlvMnB2UHI5K0c5
            SmEwYUlqV1NrZzFkNnUvQmwzSnlSKzYxdDJnCjNQODgxZ3JRRjBaeHhoTkY2NURR
            QmJmanJCejZtU1plSmxkVmpQNHJVZW8KLS0tIDdvUTNHOEdQaitVOFN3WjV1S2Y5
            TjRGRzJLT3BLNFF0UGZIMTNITkppdHMKIRV96f5eH84gZ01b28O2MsbbXw2UYoJ+
            Q9bYJtvuulth7DdCCrGbr6WPQCfhSpRl6V9EF4epubFtpMYhB7B0Qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T18:59:35Z"
    mac: ENC[AES256_GCM,data:xVwM4Qo/0/PWQmV+saMEv67gjQRf8vOE2ihd2qpjnkk1iTjjaHnaJMnYVicATfq9/8ok2euyaCQPDWtDsKIvSbVG1SKJEHyJ+WkhM9tVKncTN7Rpyo6U/TfGZwbPQagGPc8vIuJH5S20EQzKGt5AhMtIoDql4zyuc3ihCGr2xCg=,iv:V5+0FryrU6uc1Xse1lslNDJYcDhAGAxKTFUB6AEtLFI=,tag:pzPtDIF3FSEz8fKpt+VmgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
