# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: openai-api
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:4HCWxuNnmxpD8si4W8lAEIdrrN8zMNP8RMqPIQ3pCHKcAHMFAXgPnaE5c9HjgaRmpskUFX82Oe4A7kfTtF3zjeHOrcXO/ANsav2oYYt6zvoBMYuamGIuTQSG6maS/xW1gIuBCtzuxUkoywD+pJ5UG1I3Rddypf8qIzJHEejT6aM62TIHcxbOZ4bw5KeLGaBqc3UIYbY2Hi9eu919rj76T0sFW7M=,iv:FM7uzmeJvYzkTydK6/BfEuMEt7XCQA/KXNcgNeSQh5E=,tag:IG8FGODK3KNWzvg0VhBHRw==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscnBkay9mWk1mKzVlUmhq
            cWkzeFdNOTZuSTRCcnZYSnFFenljc0dxblFVClFFQW5SRjdZVGRENmloQW5MYzBo
            UlJMdi9WMG1xWjJvQytjalVUSnE4emcKLS0tIG5xRjUzV2FwZjBrcGhWM1gwdkNq
            SDBONlczbVhrSTlQcXhRVm1YYnpzelUKCjnFNdpFh80YQf3ZE1bEYgFA6Ue+zRJ+
            zGzCse9rEFFEUzXF7kMAUq1dlpA9jPGKVERIEyX4hLCOtG1m8EQUDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T15:30:50Z"
    mac: ENC[AES256_GCM,data:En2dd5hcrbAD3rTJcQq2Cv8hNNDcj4x9f2f22Tnc9A3IQRGROXKQyKi+488MVR4p5XRQCBYw+6rj/dU+S1KxX7GK3Ja1wlk6bwqXNieGMsXAqHLQgrlwcDKGwYms3bOU9jUE6rSPhfhNSQ6l3oqavs7uKyArDzPbSrpUH6ItOm4=,iv:FSJq1U5gCpJZlm2AxXoPq8mFdyxqR69iGG71NyXBJLA=,tag:7mlcKQ9blVgdURe5bvknwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
