# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: pihole-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:N7ROQmEEDrUo7Y0QbGjPdExUME5YH4Y+wEOsjxigSCWqg8Lr,iv:2rXWbAhPJmMdHTOde2x0JehYgIrk63BN8hKNIvOmXJ8=,tag:HUhpqCSuBYN9DadQ0vUJog==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eDRYQWtpZHpNWCtmOWk2
            VkV6ZDhsUTdCdWtvN252ZlMxU2NNNmVNZzE4ClRqKzI5ektqUXJaTkpwSzh0TU9K
            U3dsMzdKRitRVEQ3L3ptUUlvTWRHaXMKLS0tIGJYUUs1T3JaQ1RLbmxrR0MzQXZJ
            RVlMTVE5VFd1dXBvM09Qb05ZaE1WM1kKGlgNUrtDKqyvi6IWoky83nLOqhFX29Q4
            X/EqZJOFaPokp/LkUqM/2yHZ1NDtENSzfGul39w25wvp871Y4y0reg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T17:54:15Z"
    mac: ENC[AES256_GCM,data:gioS1c11aDDr/3AIVeGqyMC9e4OZjaOluJRR443PpN8GTQdRqJLRDhaS6VFWtw2IkFVzHNRrLHHZFP8YzJ6neI+S+I/aU8mUM6EAl27eym2UwE0fbAHy6en9qfvqxhXqYBHZSnS5oi93J3T6G4ZXkjM4PY/JhIQIRPTl3jGhEA8=,iv:bhcwxWnTG3FPltKutlCfjmpJudm37bnky90aLMW6DA0=,tag:wQhXzt8Al+1gjn9HTdoVJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
