# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:C6tvwya1TqdZ/Ih2aFzWlRRCekRmbtJ450RE/0/iYJfzT2gYbep+RgV4y3Z3vdf0N4YVUu4e+TfV5cg7AK84i3DzS7ZNBFiZLbBw2oOQQeFHLtdkU6s9vKaBkdLlGUWdMs9B111g9wXpA/25P1SURXbQBROTf7GVDiZr1m1WFaqAwGJ/EdQeG2Oj25M=,iv:J3rwYi8pOO/II5NGElwYGk0nYUnXZvObKWAaOVd9LRw=,tag:PvV6v5rmvT2y3dm7KjDYLw==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ1cvMzZJMGVPUXpwZDFZ
            OVI1aGFkdTl6bnVWNld1ckFxaThDUm54WGk4CnBPdFB4T09xWVduR3RUQjNMZ2tJ
            MmdBZ21CektTc1MxRk1CSVBmdWY2SUUKLS0tIGZjYkEzL2F3VTAwLzdhMkMxMURN
            ZTFLOEpiVVk4d2tWN29CRmFocjRPb2sK1QUEM0UNylAQ0mRqZoQILVVxoZg7QMbC
            36D6DwWMbZBPDTNjKaKnwlTwsLL1JsqLvMzICje+wQPsQ1iFLZ9Qaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T17:54:21Z"
    mac: ENC[AES256_GCM,data:KTkmDcibB8L0V4M2mborYv8SwGRw8f+4tQ5FdoEd3GDwwdGCvbO+wkKKGz/oFadNvv5qI6fxXg1oKE6W04hWFgYAJENHvyyIaGuTEtyJF4eSpc6JgcpKFh6AFgOr5+onW/4UVK1Mmguu5De80YAhxFzOC8/pKgtykxLKWP6B1lY=,iv:B8vJE+B3jTS2tRRFdaOiHluliaMvsukn3bLQg79Xvig=,tag:vZLyHcH2UifhiWaNFUDRZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
