# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: redis-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:gv8xcDbNuV+v+7CgjXqprLqL9KEGqaFIT9vHa3E+QQndke4YjpjsVHM=,iv:m2cquk/4GUBW8cCDvkyJpdHF/hLCzbptf+aJpkN03MA=,tag:03VI9+zx7Bv/CqiahZiEPg==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQmZUYnI0QXQ5M05PTEMy
            MzdxeE01eE4ybXlXb3BBUFRjUHFkVnFZSEFBCkFRS1JPMUhJeGZUeWNRRGZNV0Zv
            c1ZVWnBYT3VnQUZ3KzY1OXBvSndORFEKLS0tIFlsOUU4dDBubFUzV2R4Z1pWWWtI
            amZHZVZNZVk1ZVliMy9hdnpIMkdGL28K69hmqey45rJVCS+tTfzTdCX/LVbJYS3h
            jxw6Q5fXEgTYf8V7sfbqx1AAshXOdyMmMtVgdhkpJbgKoFuELPZsoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T17:54:24Z"
    mac: ENC[AES256_GCM,data:fqxLpfwYNq7qdFJClWWiB3rPQG4NPi0El2w59MBkOzCT/Ffd8hdIr6a3DAGLIJeRcxsv+CbzOHEcUjzD93oPaFXnbsxhNv120o7Mb0rDr5I2WJzskTml2EfgUYpTHHoAiMOln1dEElLkqMZXHO7BOTwp904TdxRYCg7TaYomQms=,iv:3t2kuYfD4bNiy2zkFkCFwp0/0/ag8EHwfdga3af2V+A=,tag:rlYWN/r1xdm/e7XtCaVAtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
