# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: terraform-secrets
    namespace: flux-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:SwLo99fgvrfmaQ==,iv:edAk8JrSQOjdJfAcOhiEwVtKlAztvi3D41MGiajFcY4=,tag:f+bWfsTx1BSoM5oVxK/b4Q==,type:comment]
    authentik_token: ENC[AES256_GCM,data:r0mj/kHWMGp5kjdgjqxUZ4G95JauzwsTr6h6e0/LWfIOcWXCh9sVjWkHNGPpo6vNpMfp8PiQTRfaEMdM,iv:2DNuafoyUIxr2NCY5MDXwcn+zylGNQ4HwwiFFQqhaS0=,tag:DLZFn680RnXyBzNkts4xSQ==,type:str]
    hedgedoc_oauth2_client_secret: ENC[AES256_GCM,data:pkZDneuef/Z5JCWNdLWyBDFQKbYm9I2MMUZzGvTn1D0IvzkRauuOr9CYPTsv8qyevhNSeYjvRswwAawPAr7pqiAhoNw+o/1gf5GGxFGGy2dISYGzwv3UWorHy5H6Ms//OWSzTQohpsCVrAMO/p/UNCjf76FG6OtIqbAPnlN4TlU=,iv:5QxraXxZmNk2TToQ7FSIJFGnelfLJppxtRhpqmuqwdM=,tag:KGYGc2yHHNQfAUlM5HmerA==,type:str]
    minio_oauth2_client_secret: ENC[AES256_GCM,data:NmVVHgxItIw8F16Th9ei8dIkXvCyazAJnJPknghAOCisOQ1zgfRtn7Ip,iv:mVcub67fzAW/qRIW7GuryJNneiPNv3ZrjGkNLRZ6eZA=,tag:zJc5C+AfT2O4g/pSefBaYg==,type:str]
    #ENC[AES256_GCM,data:LpUe885P/1qVOHM=,iv:U8sh5knOsU0hpvHk5derYf8wCbS+ytX1nfAECUCzZW8=,tag:aAMS1+27TzG6zIyP4cmljA==,type:comment]
    postgres_admin_password: ENC[AES256_GCM,data:DSsILm8ufWalN8Q=,iv:6cIJU6BsSEUUwmlZ/S1tYWftOiDP/m01t3zksVfZ1DU=,tag:imhruxX6JmvtCTJvkJXGOA==,type:str]
    postgres_authentik_password: ENC[AES256_GCM,data:+2HXOOXO3Y46,iv:7AUM7TVXLgqhWz762ZYaXF2/YnQRymqodDxNVxaBbMc=,tag:vG4VfbwC2fXHTc8gZN2iRQ==,type:str]
    postgres_hedgedoc_password: ENC[AES256_GCM,data:WuPgax4N1bw=,iv:un8wweegcZZXP+glwSDwejiS0HEDU26gFcucVoL7ygU=,tag:7bhH+wNYQ2fltC+Oz38FDw==,type:str]
    postgres_miniflux_password: ENC[AES256_GCM,data:+hxCSzM8ojk=,iv:xqfsdDpn+WQ4iOPxoH0li92Cf9Nkl1UdEQmh3lp71M8=,tag:dsvdjHmsuuHqjsuJOLklew==,type:str]
    postgres_zuul_password: ENC[AES256_GCM,data:1z+pDQ==,iv:V+M/M3Ivyq7Pkp4ZPR2zS21fqnDAW6qu+93wwLwBecI=,tag:ZoUlbHMoLj+8QDehZ5I2fw==,type:str]
    #ENC[AES256_GCM,data:pR+dRAtorA==,iv:n3dMtiwiu4jQh6xgomVmYdd7vASBF8PMm+L238PDhm4=,tag:kcGB8M5eLkZbjq/Yjr/yoQ==,type:comment]
    pihole_password: ENC[AES256_GCM,data:N5dSd6xzyi8m,iv:N3IRZpEVZuWNBYZ0EHyjiY2fsoQY466UfbLU/6VK+LI=,tag:lEaUwD6ewDl6blKLkss5hA==,type:str]
    #ENC[AES256_GCM,data:JoeJyXSY,iv:ydr66B/rj4EEtsrtw2wGKnPaRNoialGGVz+95ELycpk=,tag:KkYQWoenBLQYeF88u0NFOw==,type:comment]
    minio_endpoint: ENC[AES256_GCM,data:avln1QaCuhW0iIkmJ3VPlzR/aBXhv93YOJ5EwPjoKdScew==,iv:9mi1i61SsLwwjmv28bqVXz22+xH8jy3TKgTB04VQT5Y=,tag:71vSQ3svw5SrzktnUuMZvw==,type:str]
    minio_access_key: ENC[AES256_GCM,data:xFq6AIhjqxudB1UGQ71uA5cKvYY=,iv:FRLk8pZjct6VMIm+KWp5/9moi2FEgR8mUTjZRku1EQ0=,tag:U/dMqF0Lp4IRYRFvBQcL5A==,type:str]
    minio_secret_key: ENC[AES256_GCM,data:4S6hzljWVs6tSt+uUUdsEW2IMeiWH1zYeKtEubB7+MjL47zbb+INYg==,iv:0OFEgrmlxYnpPSTWYxS4Z/tPPvnwnpmuTvdXH61KyCs=,tag:C8/oupnt2+Lf5knI8c1CbA==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVR3NVaGozY0lxQWVxdFJB
            NnZiWEZSbnZEdHNpa0VNWnlHbGt2ZVE1cFdVCm81VWtBdG0xNCtOQlYvQVF5Zm9Z
            NEJkTk8zL1dXb0ljTWc5QVQwbHdOeVUKLS0tIDQrcWo3U2E5c0hrSDAxazNabWll
            ZUpSRnl1aDVSYW9RK2swVHRNNDRVUjQKDHFc+aaXZBBq5ilkO5wcjb0oQ1T/mGVK
            JEmqp9rVrTFa/KsoMAqu8/s+yVcADFkrmDEt1MLGdfJc+sQgUlIllA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T21:37:47Z"
    mac: ENC[AES256_GCM,data:363zOvXfQMBDXBQ74Fho0t8cxTkI5gSxrznPviZuQUXr3+NvJpgEaR4qJl7driG2PQHi0w/xftqxvrsYJy+XqndpL2Gs2qF4VOXr+4TQQS4N60M4Jv1iOzB3lOWcbNLjEyL6m3kVRYF8t7FRLWlPyGeq8Kb+Vrpfg9uHWcraQgc=,iv:vgwD9Q2AkHlKDjfo1S8OoBXbxemqemIqADCjcBW3dw4=,tag:au8zS7XnPJcXX7Z+L0Kx1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
