# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: terraform-env-secrets
    namespace: flux-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Vbxqb44b8dvxKqz6p4FnRAU9YU8=,iv:TI8BT0l+d2DHjymXdMC+8D3vhMtM5qfjr7fokAJTxPs=,tag:Mavi32+PqXdRUmDdkwRUOw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Q3rvSIc/6RbvaQeCesHjY393picN0ofCyCOfnOW42H0s3gq+IE8PwA==,iv:bi9L+TxjOkGIC7xwr8TetRhEni84+Car0DNzujpfGbs=,tag:pU52EpmgVoE8OxutTQGsyQ==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUamJaNlNKMi9CN1gyWjVw
            OG0zakowRlZCMUtCUVhPVFBZclIvS1FuUEVJCkpSeWU3VEQ5VmxIa2VHSEVET09h
            T1l5NS9MdEtSc1ZjOXh5N3dvVHNuNTgKLS0tIDNYWVB0SG1RYTluN2NTdmNFRXZX
            d0dXMUhES2lJR294N0p2Z0dEREt4M1UKpdvLXEALlZ+0t4WvTK8++/60GGoKtzXa
            J5GqZFzHPleniXEvjDajLE/Bl719epfLTcQAUUkot0k2MXn7lQ97Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T21:49:24Z"
    mac: ENC[AES256_GCM,data:bP2jL8AGK7f0SEkhsbU3gUeNIzLXalnenEqoLHIseO+vSIHyQ9CvAIocOaDYRScuXRmJVLsmIi91y1BiyjkRhCcFBSXLVXf+fMCI9577nuvK0Vx3hueTGby7ZVY0avg7myzEHBlIoUu/b1vw98hpEAaEhi0tKVkF6bHDGoSadDU=,iv:Y5zerRn0fJ1XvGKk8+QZbwnUhay3CtSPN7nNlsZN2jk=,tag:2ws36LDOiNRwEYtytJHXAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
