# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: terraform-secrets
    namespace: flux-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:QucJ522+EF2zGg==,iv:qNJqAdAuyCnipJwFYhqkVaClj9+kDVfCXoByNjOzrPo=,tag:HncTssLyTyqX9F5uoGjrfg==,type:comment]
    authentik_token: ENC[AES256_GCM,data:r+rcAmdhj0QN0+eMibPOZMbhTCljC6IJc4J0g3qPJ6zlJIq3v4PD8gzu6viJYAjjTnINK/l59Gkri4rX,iv:qh+dFGN2iEUYfk3N0gPX34MatSR5fdWKVLYKrEfxEyc=,tag:VeCTLwPnFdR12KcP7qX6GQ==,type:str]
    hedgedoc_oauth2_client_secret: ENC[AES256_GCM,data:C1h40NfOR1VUhLa0Vvq1+5XxspbEpGJnaOyBRbc5iJk3L/UGtlDVa6lqsiTZWZMJweZBCWri3Y1P8n6PjzygPPR5K96TIOee6uh8lK29EfAE+5pFgHA07Qwg6ivL7jaukVKf+a30YuDyt6U0AaMWvaRO2WLELQ5o0lJ6CoeV3wM=,iv:blB+dSCQKZTMTyVzPyN63iW5jQqihCd5Xw8/Sn6/dko=,tag:iV9jbQ8e6Z1iz7ymgNTjiA==,type:str]
    minio_oauth2_client_secret: ENC[AES256_GCM,data:+E+Gom2my5rb+m+/iRUPUK7QBGim9SMeZkGmfdRFcXZAX8cJ6gXnEIB5,iv:wm6KJmFTg7/hRCka9tiPPN1Sa6Ho8f00rZ4w/Be9i7I=,tag:VPQJLcOWGjcbqUeKVdRyNw==,type:str]
    #ENC[AES256_GCM,data:uO5BHVKor0SiIuk=,iv:+9hDbheFSvBVffvThS+GEWj6u/5/bH6bGfKNLQYbgyo=,tag:uMw/3H97RTaRZJZxvifTBA==,type:comment]
    postgres_admin_password: ENC[AES256_GCM,data:fHZp+qMCVcY7Dtk=,iv:YCZ3DKaK6LFz1G+/L2+8icGqPLcu/NNTJV786Vf3Vuk=,tag:mQo1z5DULhhD8FZwHO4EOQ==,type:str]
    postgres_authentik_password: ENC[AES256_GCM,data:qAAdiXjPBfsP,iv:LGM50jIGBWBTmbE5k2qd9T+wzD/Uh5PjRKZ3kYE97zw=,tag:OU8yidsZTtNwpzb5otu+bg==,type:str]
    postgres_hedgedoc_password: ENC[AES256_GCM,data:CONC4tpVS4o=,iv:OwVuhyMPI9kEONJ2w5KX51iY5KKSP0iuw4AdfZLBdlA=,tag:0VSKGgYLsca0NUiAEo9A9A==,type:str]
    postgres_miniflux_password: ENC[AES256_GCM,data://CDEsZKOHE=,iv:8xLZvGLfzKk1yGlquftsroDX6ova98CJOjNJJ+TTdQI=,tag:IKa3BobPVE8peYqAwFxRgA==,type:str]
    postgres_zuul_password: ENC[AES256_GCM,data:f2kJfg==,iv:d8WRQYePgMIYVx5M5wHc4Dq6UQj8LxDhwfWCbdIdK4o=,tag:0UIdzsC/sooFh1y52WqmbQ==,type:str]
    postgres_blog_engine_password: ENC[AES256_GCM,data:PBWmqc29yHg=,iv:4Fstq9FUsAfZ0bZUWus+MEy9zqTtH0dBOxhMWZfDdvY=,tag:9iAHwet4kaNniy3WP56SAg==,type:str]
    #ENC[AES256_GCM,data:+kpd0pe5,iv:8gHtrSiqf1qlZLneimj/BmjpcopC9kWN+gxT9HXKa98=,tag:eRc3y83z+7ctL1nlo0c6Lg==,type:comment]
    minio_endpoint: ENC[AES256_GCM,data:35HSCs5esopnJCZcz3cByx1zSiXa/GE1S2FOfVt+uCpVRA==,iv:fnuthqRjk68qiluR/FsXC8BbRATmxZUOft5VU35HH0U=,tag:ESnX+zykp0KxhTVWP0zIsg==,type:str]
    minio_access_key: ENC[AES256_GCM,data:RvvRKe9gpcOGL/kL6AiB7k9ucd4=,iv:L4NRtd/T+P41KdG8bgm4HTb5h7q4JTua6zQR6VBmxy4=,tag:kuZSTRxHmPj8k+j7+8w2Rg==,type:str]
    minio_secret_key: ENC[AES256_GCM,data:m5W+IWCHY0mJlOrsndKNLYbWmox8iVYPydhUiKJj2NEzqnlkQQF9OA==,iv:9qdP3H9zRPK7EquCNtED7eXk5PQMsjYBMdGlwh0iBJI=,tag:30O31FGi58PAF2AI4m5cmA==,type:str]
    #ENC[AES256_GCM,data:DA/5wmPS5+ifLgI=,iv:UuMUI95ioFW0jBThjN1UtwYMWwzH5evGkP9BjSOLy7E=,tag:GuYHaZGxtf3Hk0knLGlARA==,type:comment]
    cloudflare_api_token: ENC[AES256_GCM,data:3XbuR5zeK82NRYgK04eqyEgwuzUzTVUTdrya9KJG5dgvN7EHoNicyNlfGbvDiiCMyW7BhOk=,iv:p4HbdnX8Q7jfLIOxOVt4bgYZYLhQ4ivbx7UqIyJgS5s=,tag:rReu59eyqXYJL5csrGUFjA==,type:str]
    cloudflare_zone_id: ENC[AES256_GCM,data:1pa8YGv/5K6hy68x2oB3QPfuwkw69bz0BObFxoRNmLE=,iv:66hxlojsMo13zKuLiptf6bNF73PlhdD2ywcAeHNC6RU=,tag:JhGPz+L+6aDqHiBZMvcb/A==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM3NlcWFhUnExSWFndlQr
            VFljelVPMmpyZmpWN2hnd1JUNEkzOVcwV3drCmJvWlNjZEluVXp1Qkp0UXNTVTR0
            cy9uN0t5RzZiQ0FyK2RuM0VEZk1DZ1kKLS0tIDcwMzJJZHhUclFza0dMa0IvMTJj
            a3ZYZ0ZmQXo2QVpZZEhMRWNqTXF5SmsKSW0a7lqRTNErbnluFVGmAMhVdWjIMHaI
            DGo8bR8NFups3jOtmbiZmoIqcDLc0t2JS5WaTsjNHpjmrcpxtlkbow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T17:20:05Z"
    mac: ENC[AES256_GCM,data:wVhwsTp7i0JhGrWx7r+UncLOfiFBsSmQAzwzdHP0QQsdcvUXVBSs3uGnwh9V17R4qjXUuU3QGdzD1X3KPnG03iGitW0r6sxw4QqeYeUm1z1Zf/ljndehqg4eDh0lm8kapYBTPESxi/EXY1sKoFxy3N9SdE3INhPDafC9FIlPulM=,iv:sshy6FGddw1RSwcQzv2YCof2I/VXBBQNfXR02ebd5FY=,tag:krtqFh5zedSftyMNfrziUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
