# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: terraform-secrets
    namespace: flux-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:f23pmMGIkLS6mw==,iv:8cnmR4vFo1zsmADajy1prRMRbIwQL7cIMSNlbY5Zbu0=,tag:kLDKvxQpseV5AOFPhr7Vbw==,type:comment]
    authentik_token: ENC[AES256_GCM,data:avKg4sNsd/kpDbOJkozWyMAWX7QpgAkj0NVbaL+Tu0LYA9UeuI7q7e6z0vZRc3/LwqUywMxPM8xFJKpk,iv:oJ/HH5d1n9Heg9sdQXJ6O3Y3gpE4H59M5e7lRqO1mQo=,tag:WmXdso5mtwX3/ZngkaeN6g==,type:str]
    hedgedoc_oauth2_client_secret: ENC[AES256_GCM,data:tkoGTJw3vBR32FE7zNZJWfU3cc+jtDLRJWOEP/7LkSo94szuTrN5CbK1ASPThgBZ5bX8dRtQH07L/NHNRf48LnzgP6mFg/6fGziGGJ14LHaK0jI9SuFdKN8jjQRvj7g3JUFzksk0tZCUMUOgyEUtwzpRm1aUI/lONzAG2mxxhNs=,iv:/CVv1r5jlZCrkiBvE/qupyYGOEOHygraiviKoDyuUw4=,tag:X7hL1N8PYLGx/eGR4zoJKw==,type:str]
    minio_oauth2_client_secret: ENC[AES256_GCM,data:Y+ZehHtmT2WxZ74C0aeTfXFarfyZUe22ACRQRltba81IrD2Q40utS6Nz,iv:SvY8gObut2zPcxxS9lsoMe4TxVLj8L6J62q8T9CpqM8=,tag:2y35ogm3tycZwrxFTqg5lw==,type:str]
    #ENC[AES256_GCM,data:jV4q64o4ZexO3ik=,iv:5ioYyEiBY54iDtsvIEyaFm6m8BqS04iFL5fs1bWXlSI=,tag:bzRUmCEx8B0lpS+LJiN9pg==,type:comment]
    postgres_admin_password: ENC[AES256_GCM,data:cOL91q82RNeOfmI=,iv:ClvCXrQ3VtqzzK73Ddaft3AXv7R5WqM4Aw4VVYvDNV8=,tag:p/4cZMt7Blb88kP4mz3vhg==,type:str]
    postgres_authentik_password: ENC[AES256_GCM,data:qxD5HyKTxTvz,iv:0gzWatk2GKdNW1Wn8j0XbCB8HzT9uefDrp+0dyoCgvk=,tag:qz9PCA8S1g4CyKcn93d9sw==,type:str]
    postgres_hedgedoc_password: ENC[AES256_GCM,data:lzbSA50vu5U=,iv:hHh5EQXrpTN0eLTwLsM0YCEADxLMkTzB3bFomneis+4=,tag:zeRyIc/zfI+GR6cLO5sy2g==,type:str]
    postgres_miniflux_password: ENC[AES256_GCM,data:B+0RiTO4EMk=,iv:RpmeFYjETZmrEfHLHwELFd114cpRm0jWJaji4E2TLGk=,tag:rFklV7x5XZweTZse3PP/IQ==,type:str]
    postgres_zuul_password: ENC[AES256_GCM,data:AziZ/w==,iv:7S8yjHiqiOj7SZZCzAoU5OjZ2ODlHJ/yzjw5gQsT010=,tag:QmPNAgHCWVAtbfRTM02X5A==,type:str]
    #ENC[AES256_GCM,data:p47ab080,iv:Ea7z5HVoXpDhpMvUjXfWLz3cstSxtW3cb74Z86lUYXg=,tag:8phgGbV5VMomwuMGRsZn4w==,type:comment]
    minio_endpoint: ENC[AES256_GCM,data:mvN1B0XIuAgYlR0Pg4RY8ednb6blH5tnZXDDRHBx8a9t6A==,iv:sQFyiWndPQEv+YLzG+SAnxvim1yz/ELrfjRVHHtX5WE=,tag:Ojr71MSdvYQl8UNqD7NCQQ==,type:str]
    minio_access_key: ENC[AES256_GCM,data:Vd9DfXE1wUOpZGQEoVQdPjK+LQI=,iv:kWTvq2Ka/PErGrXkzDdkPPsy6kCJyAanGz9Tx6qW3v4=,tag:lM3ppuSdbksdEWtgNDpkeg==,type:str]
    minio_secret_key: ENC[AES256_GCM,data:18n5exkuWt1+WsGGXN1PsvblluDnKeUKFx82So0Grhrb8UhczRxRhg==,iv:1ZeBTRoM7vxTkHYcGbbCbT45aqa0Ejzq7OXPDc4BFeI=,tag:egXJ2Xr3BWU4Mg7lBIxARw==,type:str]
    #ENC[AES256_GCM,data:3CtX7xttET6WWaQ=,iv:aPMORQE0R4WKbBMfm3EUlM1ssySzw09RhqZnMedgLS0=,tag:7pT1a7NfGl2D3sYNSb5WMQ==,type:comment]
    cloudflare_api_token: ENC[AES256_GCM,data:F0Kk05ZVLUIUXYQ+eAS6gqSdczp0FJPQRmO/KMe1aU055EBGA1Vdq0UzfUw2g124ELmLzno=,iv:3xN4iNbivUg1imw+qn8po5lS5k3yK7Ee94JiMpFs8ZA=,tag:oGNDv0JawCqotQiPcINySw==,type:str]
    cloudflare_zone_id: ENC[AES256_GCM,data:7aFnRCAjjOXv+1ysOcsA0PurNRHeeSBh+UNIB0IpEmc=,iv:oam4vewfTq59+pvPWEbLbekEXhV0Lf7zKMc2ebffgqI=,tag:5xvN2BF0LSf6T2sfCcbVCw==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TnpYYW40VjJrVXppMXZi
            VjljVUZWSkRURnZZUVVacWF2eDU0WDBCcFc4CmVHc2V1MVJrRUZTOVJMMlRjWW50
            ZDN6YndUY2pmci80M0dsdzllSFh4NFUKLS0tIHY1dXFzekhJT1lheWFkTHBDc0Iy
            dDRQMFQ1alBuLytHVHlrRElVUWtFRUUKW0Ve0GXWJYk9Ao+zxTFMVz3aLL8fOJSM
            xIRAifqZbEdTwacWiHqoDlXYzppVczbVOhfu2GVVwZVb2bwN2eehjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T19:54:18Z"
    mac: ENC[AES256_GCM,data:BgRCOYSW758xaDS3Ld+CWixHhjq18QVbNcTUOJUWLXvinCx2jAWBxoLi1eLohyGkxlQfo4bf3wDhnRY/Yd1yJZm0gow0Xxtw0sTmSHdK42I+drzd0JtXvYMwa39KGcXa508+kjFUdoeN+xWN+A/PQngcs2dcqJjym6M4ed2P92Y=,iv:3R1yoid+umhE8XMd0a/Y5acbZFYO8dfnv/FjW7vUm1M=,tag:jHU2tnpBaaFOEAeMyI/8Sg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
