# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: zookeeper-tls
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:5mxblBcBmd8ivydHxoJXac80foxCNfUxnU65JyggkMNAzXQ4PorRcqQOycPd63n90txdT/5CpnfHXvvXh3WKA+4awgPN+IqLsJc1qgE7venWpNFClgF8xKJb2K48Q8al3dlRyZNJS6tM15n2/d7Wwz8xJ6OQIhwsg7C4Y5Gs1Wsm6YDAb5bma7qOZajv4sXBohjheAS5s0bnIPCm9Wy0cKNfsqxLnCEk7UjmTtnWNi6ZoQittCmdI88A5HhKfnEoDXgVUpIaxpjfhnOqOf8Z72MozAxeJwIYMLQv3b31a1xXrd3F93o=,iv:P1oJwnk/7F9rmlb3gn3ggh6Q9zgs+oVb0+qzNbCP0u0=,tag:AL7+k3RDVAiY/t+GV2xyoQ==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VjhxSzl6WmFXT2sxT0JO
            Qk1BOHFHZ3hrNUpyYWF4STZVa2xPdVBuZHo4CkdrYTVkdzFNb1dvZXpRLzY0WlBh
            OFZwemg0WlRHRWgrWk5VVDg1Y3AzcncKLS0tIEZTZlNPNGF4NUJNeWdFL3pCZXlv
            dVZvUVdWaytuYzkyUDd4cW5tM2NsRk0KURrdhv6SmjJ0IYG3D4iEfoHkiVWyCH/7
            gcV5aExizlypWDKlrgxg+pmNvF5Qm+xec3R9K+1Fo8nQP7M/HrvdLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T08:29:36Z"
    mac: ENC[AES256_GCM,data:/GYaa1bNhGYtdCJNCh0I38d8F5kkKuqa4uJu2N4CP25QKswos5s+Uq3E0K2po761FNG1d7tSGUAnWGflfv7K8BRPq0nLppfdE8Fg1faXrwzFdf99L/kSBrDgmo8nep2jHeksIfJnriU4P38EHrr/DjNf/q5M+2FoNXllJnVb4Tk=,iv:bDPcs++4f00jaf/XqApvjI13PoTaEy1kPKN7MY/oY6g=,tag:5tWHjzTMuNn1zi5fTjQtkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
