# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: zuul-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:8oPYZ80n20pEKvYMLoSS4RLKLVGaNfRixpczN4sl41cg/84Lsq94ni+zfav88aoBFuaLGwkydnogoBjYr9W03MPiCdNgO13LSoN+DWRE+Ca+d9DiccVOGzfnRGMvnZG60ayDkFqTavc+TVROvahjpIRnaVzsXVMeHgHDOvY59wCOz9ckdU4nRUuQ0nUXbODNJh+ZB9PW7Ur+kzi5TjgjaUDcBkQTOci2L9+HPG84kHTxyrEt9Yb+tiPMOflJynoq/l000SWNjfIClAacwLZC/gAqxGmFnn8CdamRiwZJn1CWUa8lyCqPkvSWOv0/aj/Drbrmx97/BJQsBkdbCHI1yyvOXpH1fn5natB4uHxA+r+/fgzcN7NfkuPGDP6feDhS0sSSom44z962SisGSPWJQv3T48DviHuywnSpzaRf3hYl3DmrARLvfzn7967HwOsGHDBYmmMdc+kOU39XrlAInRFOGXqNHBzwqKpoBMXK7sfxw6Vqr6FKhOl0W8GBR3qMhEo96ePidOyB2k/4QWfoADWyLknbCu549U/e6zFXSXZvb/PWD1Kzv+G69PvUtmW3SMGAOXljWdIbhOQHyAMWYjzLlxjOSWxeygGk4G99oxhKI5ygb6eHxYY4kV2rn7XSxP4ix2u7/rUUnUg/mbiWy0d47ORBXmnNFZh1cddm/jTVhSjV1DXxplt8MQ7GbBtcvneF9/Z+16WfukKN4e20QCbBEkrxv1XssCEFLV07alFnfceQbzvUOiTOfiNW35lBJD9QJ1CKW9WP4lG4PGjGFO6rAjwC1LP7y6QpNFI7YdLFHyIfB9O92KPkzYk=,iv:MVNWaYJHkLHctwTKKmZwMGY6amayQ/iZqMAPB0gaeNc=,tag:eQPVTA//IGgS38NLSKkR1A==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3djJ4UWtlQTV6ZEFkTDlo
            Szc0cEYyN2I3RXhoQUYyQmpHUVNhSUthMERJCnVVRXBlV2hPYThxU0J3M2d2YzhX
            TDNudXJ4UHV0d29lQzBJdnR0U1FNUTAKLS0tIFdhdE95YS9MRUltM0IxdldDQ1Bv
            eXdha09nbEVzdWxVbGovSzdYdklwWjAKg5qVUXYb/6mB6IhmMvOgWuGXCxwFyn+q
            GJ4fp9U0fxnB4eaCP5hGvnebpFqdSNjnH8iVlNMPQdAVJt06gHbPOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T09:44:22Z"
    mac: ENC[AES256_GCM,data:LeXRUXREFY4pGtDFe+0J4YMm31WDEXgG3Ne9nE4bfG/PbyO5XNqPmI1+4eQJvVE5ZXXTR9cNn9o8ZzyGPeOqSNUhBNPR+bqyJcWal37sfITiZJkDHxhCWVw9we0q0weasXj58vJFIK8tGRSflf6Yjq7DErm3HWX7MpGmJ92DT20=,iv:WorfQtBZJPb6zSstp9zT3rheei8+ezwrlJ8PvHAbNpg=,tag:5X8hWzSr44RtycbhzvLZZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
