# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: zuul-secrets
    namespace: flux-system
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:gd5OAi9Bh3hMMCXA8jzBP3mNcJ08+dlgkIWny4UaRoWikCE5sbIZ4fhfJ+XzgMt19KkCUD13mobUEm0ARGWG58VeNanizTRzeIhtZtivLP+U24qVe1yJJxgHMrXv2DpkIrgz0HvukSdCqOeUJgKyelUKWPWiTh6AKXaVmAWfFTNf5hlKPzUdPfvZMXPecJORQkJjnHso68jUay94J3rol6nHpqSImvqoCctWfxVCoXCH/JBStOHjwvio6ipc95IH3i9CaFbl+93NGbb6UbQr3ykTX45/Z2ylrlH0SFRSiUPOF4+Ue5hw7IUUOg3QO1aJpqkuAuuJFEeXkGq7lZeTapRhEMZb06u9Rc2Ro2DOer6xz5OVGAf5SR9KdBT5fbRv4zTqMUaXxeOWZjPJ6QWjchhK8+XHlbq+FhFc1DtUuxVeOKfukMuJUQu+aBMPokzsEf2CqCqNPIzfOq68jrAAktV/yxpF38nuALbZGVW7jNA3vupEkQ5gsW2IbytyudSrDEIisa0YzO0xTdDorP+BkxoHq+KijTNH+tkozWinZ4bhFx1OeFXhmOM/L9fnrdB9RXXCyUgzsWbkfy1FlNFDHwGF5cuhzlBwBDwdNl9vFAwjRBTdo5vNyiz7MUeBi1J0fEpU7CpD+zP/HSWLixDjoE4OkI4rJWSTnaWLxpG+SKB3QkIyo//FdHU5fYcGr2P29VjHOYaGYCoEB3gHyr3Gy5fDGkII6iABK8o4IukRtsm3YCwhkM/sOo8E1CgLdCOEimLzC5f0GIA92Q1hTw==,iv:cLl6ffM0wSTtPG7ESsZCOCEHiLDeXnKkdjLPZ9j0Ox4=,tag:iRFy7+hK5X0zbHOlWMLcNg==,type:str]
sops:
    age:
        - recipient: age155k7zzfpc2fpflme9t7tvutulsznh8eqpgv40ldrlu9a5spfks3qld7aav
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDV083c3lPVGFnaWtvZE40
            c0t1anZneHV1YXVzQjVWd0R4QkY5RDlSdUNFCkZpVitjYUJWSXhlQVBNVnVuMGRG
            NU95T0hoTkF0Q3VBQSswRVVZeTRQa0EKLS0tIDVhRW1jUmtuWHR6ZVEydm1wUjR3
            a2Nod0NpeUNDUXcyRWNsZGF0K1Y3Sk0KeSnIAv9bnWTh0zZnKLEnxXizpyuybgKh
            ks1ofsYe3I0Ath6IGr4XzL2z0Lk4VhaR5MiGf1eArPsI5PzuIBBitQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T17:54:28Z"
    mac: ENC[AES256_GCM,data:boKa9PcN7uFNBooZ0I9nGzZARODCy2bajEIg3IYQxQUOeWEz48jCdUubXhvD3w8YZVb6KqbbPF0Hsn2mUKrju92oiXCV5qLDNnlkwTXp+WRZCVn0B/XMOT0QSjMgFfTVA6E+odBva5d7QbNsUvq+Yny89f2trELZafCjywB+Bhg=,iv:nrBrFaCtKJU7oe2H9eci2eIKfwGW+wZog+CaK0bVpUg=,tag:T8xDgEg5oKeZVa6YvmLDhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
