---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docker-registry
  namespace: flux-system
spec:
  install:
    createNamespace: true
  releaseName: docker-registry
  targetNamespace: docker-registry
  storageNamespace: docker-registry
  interval: 10m
  chart:
    spec:
      chart: ./production/kubernetes/helm-charts/docker-registry-wrapper
      sourceRef:
        kind: GitRepository
        name: gerrit
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: docker-registry-secrets
      valuesKey: values.yaml
    - kind: Secret
      name: production-output
      valuesKey: registry_access_key
      targetPath: docker-registry.secrets.s3.accessKey
      optional: false
    - kind: Secret
      name: production-output
      valuesKey: registry_secret_key
      targetPath: docker-registry.secrets.s3.secretKey
      optional: false
