;; Треугольник Паскаля

(define (paskal n)
  (define (getvalue pos line)
    (if (or (= pos 1) (= pos line) (< line 3))
	1
	(+ (getvalue (- pos 1) (- line 1))
	   (getvalue pos (- line 1)))))
  (define (displaystring pos line)
    (display (getvalue pos line))
    (display " ")
    (if (= pos line)
	(newline)
	(displaystring (+ 1 pos) line)))
  (define (maketriangle line)
    (makespaces (- n line))
    (displaystring 1 line)
    (if (= line n)
	(display "done")
	(maketriangle (+ line 1))))
  (define (makespaces x)
    (display " ")
    (if (= x 0)
	(display " ")
	(makespaces (- x 1))))
  (maketriangle 1)
  (newline))
