(define (make-account x password)
  (let ((pass password)
	(count x))
    (lambda ( . l)
      (if (eq? (car l) pass)
	  (cond ((eq? (cadr l) `withdraw)
		 (begin (set! count (- count (caddr l)))
			count))
		((eq? (cadr l) `deposit)
		 (begin (set! count (+ count (caddr l)))
			count)))
	  (begin (display "noway")
		 (newline))))))
