(define (make-account x password)
  (let ((pass password)
	(count x)
	(try 0))
    (lambda ( . l)
      (if (eq? (car l) pass)
	  (begin
	    (set! try 0)
	    (cond ((eq? (cadr l) `withdraw)
		   (begin (set! count (- count (caddr l)))
			  count))
		  ((eq? (cadr l) `deposit)
		   (begin (set! count (+ count (caddr l)))
			  count))))
	  (begin (if (> try 7)
		     (call-the-cops)
		     (set! try (+ try 1)))
		 (display "noway")
		 (newline))))))

(define (call-the-cops)
  (display "Stop right here, criminal scum!"))
