(define (make-frame variables values)
  (let frame ((var variables)
	      (val values))
    (if (null? var)
	`()
	(cons (cons (car var)
		    (car val))
	      (frame (cdr var)
		     (cdr val))))))
(define (frame-variables frame) (map car frame))
(define (frame-values frame) (map cdr frame))
(define (add-binding-to-frame! var val frame)
  (set! frame (cons (cons var val)
		    frame)))
