---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-bundle
  namespace: flux-system
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDDTCCAfWgAwIBAgIUI/fmbmEZCUzejueo4m2yJAtqcG4wDQYJKoZIhvcNAQEL
    BQAwFjEUMBIGA1UEAwwLbWluaWt1YmUtY2EwHhcNMjUwNTIwMTQ1MjI1WhcNMzUw
    NTE4MTQ1MjI1WjAWMRQwEgYDVQQDDAttaW5pa3ViZS1jYTCCASIwDQYJKoZIhvcN
    AQEBBQADggEPADCCAQoCggEBALuhSitDVAZj4SQ3tnFNllGhgwnU+V1WhbDs34XM
    /ECCJgTpAWtUrUAvfIsR3kufvgWrH3EHsscCzG5iofiV2x4SVaV1hqhwFucztKls
    z0OJf434gCWONtwXOQaqCoTz+geeK50QcWvLnnih3js5KL4XfV/Txk89jrv9LegJ
    oK15IFgxd4aPxf5ojEhc4AX/8/XQtSUefID27YPOnAi0YMzPstM9WloGMMbn2ymL
    0QeROg6qZ8KkcWAnU/vnbhKAaix/EJGTUxOLqlZ5J1rBQQgaReMFv7wbPSzMyQ/u
    ldGgQS7piRf+uDUib4blXflmqIFW47rZp8zH3HKSHCv7/0cCAwEAAaNTMFEwHQYD
    VR0OBBYEFOKslB+d8vnGWMvjlnCl4hW5kdDnMB8GA1UdIwQYMBaAFOKslB+d8vnG
    WMvjlnCl4hW5kdDnMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
    AI4XU2NexseQK0P4PHy7sJ1XxGenfDUb+5U1mK5NwmH1th42kFmCc+9SfpOp05vN
    1Nvndq1MOW+sU13VGirYAjAJRH/W8OBgw5UITj4MekOdTYPALmt5PFCNLf4j49Md
    NKEpI4e8W7wHUv50M1lKR5kOUx3QrPCRzoVSsH+Tajt46VcyLxORRn626wHgsC9w
    HaL7kmK0CIhAHk1nhJIIz8f3F/U6TTE+6e6RWjo+EYE+u79xHjLdfpsTaNZvUDZ1
    sAm8RWu1rp9TF0tXn158HuKXKzFgP9U0ig78tDNr3F9Izpw8+1YxqmgP1U0VSSwO
    Uba/Tf4BdXY8b7+GPNz2mW4=
    -----END CERTIFICATE-----
