---
apiVersion: v1
kind: Secret
metadata:
  name: minio-ca-cert
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  ca.crt: {{ .Values.caCertificate | b64enc | quote }}
