(define (make-monitored proc)
  (let ((count 0))
    (lambda ( . l)
      (cond ((eq? (car l) `how-many-calls?)
	     count)
	    ((eq? (car l) `reset-count)
	     (set! count 0))
	    (else (begin (set! count (+ count 1))
			 (proc (car l))))))))
