(define (rand ( . parameters))
  (let ((x (rand-init)))
    (cond ((eq? (car parameters) `reset)
	   (set! x (cadr parameters)))
	  ((eq? (car parameters) `generate)
	   (set! x (rand-upgrade x)))
	  ((eq? (car parameters) `get)
	   x)
	  (else (display "Error")))))
