---
apiVersion: v2
name: metrics-server-wrapper
description: "Wrapper chart: metrics-server"
type: application
version: 0.2.0
appVersion: "0.8.0"
dependencies:
  - name: metrics-server
    version: 3.13.1
    repository: "https://kubernetes-sigs.github.io/metrics-server/"
