---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-config
  labels:
    app.kubernetes.io/name: kubernetes-event-exporter
    app.kubernetes.io/component: event-exporter
data:
  config.yaml: |
{{ .Files.Get "files/config.yaml" | indent 4 }}
