---
local-path-provisioner:
  storageClass:
    name: local-rebuildable
    defaultClass: false
    defaultVolumeType: hostPath
    reclaimPolicy: Retain
    volumeBindingMode: WaitForFirstConsumer

  nodePathMap:
    - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
      paths:
        - /var/mnt/local-path-provisioner

  helperImage:
    repository: busybox
    tag: "1.37.0"

  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

  helperPod:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 100m
        memory: 64Mi
