---
apiVersion: v2
name: envoy-gateway-crds-wrapper
description: "Wrapper chart: Envoy Gateway CRDs"
type: application
version: 0.3.0
dependencies:
  - name: gateway-crds-helm
    version: 1.8.1
    repository: "oci://docker.io/envoyproxy"
