---
apiVersion: v2
name: observability-wrapper
description: "Wrapper chart: OpenTelemetry and VictoriaX observability"
type: application
version: 0.5.2
dependencies:
  - name: victoria-metrics-single
    alias: victoria-metrics
    version: 0.45.0
    repository: "oci://ghcr.io/victoriametrics/helm-charts"
  - name: victoria-logs-single
    alias: victoria-logs
    version: 0.13.9
    repository: "oci://ghcr.io/victoriametrics/helm-charts"
  - name: opentelemetry-collector
    alias: otel-agent
    version: 0.170.0
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
  - name: opentelemetry-collector
    alias: otel-collector
    version: 0.170.0
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
  - name: kube-state-metrics
    version: 8.4.0
    repository: "oci://ghcr.io/prometheus-community/charts"
