---
- hosts: all
  gather_facts: false

  vars:
    bazel_target: //pipellm/...

  tasks:
    - name: Run pipellm Bazel tests
      ansible.builtin.include_tasks:
        file: tasks/run-bazel-test-target.yaml
