---
- hosts: all
  gather_facts: false

  vars:
    image_repo: registry.your.domain/zooreader
    image_tag: "rc-{{ zuul.commit_id }}"

  tasks:
    - name: Promote the Zooreader image
      ansible.builtin.include_tasks:
        file: tasks/promote-container-image.yaml
