---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zooreader
  namespace: flux-system
spec:
  releaseName: zooreader
  targetNamespace: zooreader
  storageNamespace: zooreader
  interval: 10m
  chart:
    spec:
      chart: ./production/kubernetes/helm-charts/zooreader
      sourceRef:
        kind: GitRepository
        name: gerrit
        namespace: flux-system
