apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zooreader
  namespace: flux-system
spec:
  install:
    createNamespace: true
  releaseName: zooreader
  targetNamespace: zooreader
  storageNamespace: zooreader
  interval: 10m
  chart:
    spec:
      chart: ./production/kubernetes/helm-charts/zooreader
      sourceRef:
        kind: GitRepository
        name: gerrit
        namespace: flux-system
  values:
    nxs:
      deployments:
        zooreader:
          containers:
            zooreader:
              # yamllint disable-line rule:line-length
              imageTag: prod-1783709761-8e5df05901871157e3f6831ecc6df2f8bc5c6fe6 # {"$imagepolicy": "flux-system:zooreader:tag"}
