---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: zooreader
  namespace: flux-system
spec:
  image: registry.your.domain/zooreader
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: zooreader
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: zooreader
  filterTags:
    pattern: '^prod-(?P<ts>[0-9]+)-'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: zooreader
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: gerrit
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        name: Flux
        email: flux@your.domain
      messageTemplate: "zooreader: Deploy promoted image"
    push:
      branch: master
  update:
    path: ./production/kubernetes/flux/apps/zooreader
    strategy: Setters
