---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: production
  namespace: flux-system
spec:
  interval: 1h
  parallelism: 1
  path: ./production/terraform
  approvePlan: auto
  writeOutputsToSecret:
    name: production-output

  sourceRef:
    kind: GitRepository
    name: gerrit
    namespace: flux-system

  backendConfig:
    customConfiguration: "# Override"

  runnerPodTemplate:
    spec:
      # AWS credentials
      envFrom:
        - secretRef:
            name: terraform-env-secrets

      # Cluster Issuer CA
      volumes:
        - name: ca-bundle
          configMap:
            name: ca-bundle
      volumeMounts:
        - name: ca-bundle
          mountPath: /etc/ssl/certs/ca.crt
          subPath: ca.crt

  varsFrom:
    - kind: Secret
      name: terraform-secrets
