---
apiVersion: v2
name: postgres-ui
description: "Wrapper chart: postgres-ui"
type: application
version: 0.5.0
appVersion: "4.8.1"
dependencies:
  - name: nxs-universal-chart
    alias: nxs
    version: 3.0.21
    repository: "oci://registry.nixys.ru/nuc"
