---
nxs:
  releasePrefix: "-"

  generic:
    usePredefinedAffinity: false

  deployments:
    postgres-ui:
      replicas: 1
      containers:
        postgres-ui:
          image: adminer
          imageTag: latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 256Mi

  services:
    postgres-ui:
      type: ClusterIP
      ports:
        - name: http
          port: 8080
          targetPort: http
          protocol: TCP
