---
apiVersion: v2
name: authentik-wrapper
description: "Wrapper chart: authentik"
type: application
version: 0.10.0
dependencies:
  - name: authentik
    version: 2026.5.5
    repository: "https://charts.goauthentik.io"
