---
authentik:
  authentik:
    enabled: true
    log_level: info

    postgresql:
      host: "postgresql.postgres.svc.cluster.local"
      name: "authentikdb"
      user: "authentik"
      port: 5432
    redis:
      host: "redis-master.redis.svc.cluster.local"

  server:
    livenessProbe:
      timeoutSeconds: 10
      failureThreshold: 6
    readinessProbe:
      timeoutSeconds: 10
      failureThreshold: 6
    startupProbe:
      timeoutSeconds: 10
    resources:
      requests:
        cpu: 100m
        memory: 384Mi
      limits:
        cpu: 500m
        memory: 768Mi
    ingress:
      enabled: false
      annotations: {}
      labels: {}
      ingressClassName: ""
      hosts: ["sso.your.domain"]
      tls:
        - secretName: authentik-tls # pragma: allowlist secret
          hosts:
            - sso.your.domain

  worker:
    livenessProbe:
      timeoutSeconds: 10
      failureThreshold: 6
    readinessProbe:
      timeoutSeconds: 10
      failureThreshold: 6
    startupProbe:
      timeoutSeconds: 10
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 768Mi

  postgresql:
    enabled: false

  redis:
    enabled: false
