{{- if and .Values.letsencrypt.enabled .Values.letsencrypt.cloudflareApiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  labels:
    {{- include "cert-manager-wrapper.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.letsencrypt.cloudflareApiToken | quote }}
{{- end }}
