---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway-crds
  namespace: flux-system
spec:
  install:
    createNamespace: true
  releaseName: envoy-gateway-crds
  targetNamespace: envoy-gateway-system
  storageNamespace: envoy-gateway-system
  interval: 10m
  chart:
    spec:
      chart: ./production/kubernetes/helm-charts/envoy-gateway-crds-wrapper
      sourceRef:
        kind: GitRepository
        name: gerrit
        namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  install:
    createNamespace: true
    crds: Skip
  upgrade:
    crds: Skip
  releaseName: envoy-gateway
  targetNamespace: envoy-gateway-system
  storageNamespace: envoy-gateway-system
  interval: 10m
  chart:
    spec:
      chart: ./production/kubernetes/helm-charts/envoy-gateway-wrapper
      sourceRef:
        kind: GitRepository
        name: gerrit
        namespace: flux-system
  dependsOn:
    - name: envoy-gateway-crds
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-edge
  namespace: flux-system
spec:
  releaseName: envoy-edge
  targetNamespace: envoy-gateway-system
  storageNamespace: envoy-gateway-system
  interval: 10m
  chart:
    spec:
      chart: ./production/kubernetes/helm-charts/envoy-edge
      sourceRef:
        kind: GitRepository
        name: gerrit
        namespace: flux-system
  dependsOn:
    - name: envoy-gateway
    - name: cert-manager
    - name: authentik
    - name: docker-registry
    - name: gerrit
    - name: hedgedoc
    - name: minio
