---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-ui
  namespace: flux-system
spec:
  releaseName: postgres-ui
  targetNamespace: postgres
  storageNamespace: postgres
  interval: 10m
  chart:
    spec:
      chart: ./production/kubernetes/helm-charts/postgres-ui
      sourceRef:
        kind: GitRepository
        name: gerrit
        namespace: flux-system
