---
apiVersion: v2
name: zuul
description: A Helm chart for Zuul CI/CD
type: application
version: 0.12.0
dependencies:
  - name: nxs-universal-chart
    alias: nxs
    version: 3.1.0
    repository: "oci://registry.nixys.ru/nuc"
