---
gerrit:
  server: review.your.domain
  user: zuul

zuul:
  imagePrefix: quay.io/zuul-ci
  zuulImageVersion: latest
  nodepoolImageVersion: latest

  zookeeper:
    hosts: zookeeper.zookeeper.svc.cluster.local:3181
    secretName: "zookeeper-tls"  # pragma: allowlist secret
    tls:
      ca: /tls/client/ca.crt
      cert: /tls/client/tls.crt
      key: /tls/client/tls.key
    certManager:
      enabled: true
      issuerName: "ca-issuer"
      # issuerKind: "ClusterIssuer"
      keystorePassword: "changeme"  # pragma: allowlist secret
      # duration: "2160h0m0s"
      # renewBefore: "360h0m0s"
      # keySize: 2048
      # additionalDnsNames: []

  scheduler:
    count: 1
    storageSize: 80Gi
    storageClassName: ""
    config:
      secretName: zuul-tenant-config  # pragma: allowlist secret

  executor:
    count: 1
    terminationGracePeriodSeconds: 21600
    sshkey:
      secretName: gerrit-secrets  # pragma: allowlist secret

  web:
    count: 1
    statusUrl: https://ci.your.domain

  fingergw:
    count: 1

  nodepool:
    providers:
      - name: dev-k8s

  connections:
    gerrit:
      driver: gerrit
      server: review.your.domain
      user: zuul
      secretName: gerrit-secrets  # pragma: allowlist secret
      baseurl: http://review.your.domain

  webMinimal:
    image: registry.your.domain/zuul-web-minimal:1.0
    imagePullPolicy: Always
    replicas: 1

  tenantConfig: |
    - tenant:
        name: your.domain
        web-root: https://ci.your.domain/t/your.domain/
        source:
          gerrit:
            config-projects:
              - zuul-config
            untrusted-projects:
              - src

  nodepoolConfig: |
    labels:
      - name: build-node
    providers:
      - name: dev-k8s
        driver: kubernetes
        context: admin-cluster.local
        pools:
          - name: main
            labels:
              - name: build-node
                type: pod
                image: registry.your.domain/build:1.0
                image-pull: Always
                volumes:
                  - name: pre-commit-cache
                    nfs:
                      server: 192.168.1.185
                      path: /srv/nfs/pre-commit-cache
                  - name: nix-store
                    nfs:
                      server: 192.168.1.185
                      path: /srv/nfs/nix
                volume-mounts:
                  - name: pre-commit-cache
                    mountPath: /root/.cache/pre-commit
                  - name: nix-store
                    mountPath: /nix

database:
  secretName: creds  # pragma: allowlist secret
