---
apiVersion: v2
name: postgresql-wrapper
description: "Wrapper chart: postgresql"
type: application
version: 0.5.0
dependencies:
  - name: postgresql
    version: 18.5.20
    repository: "oci://registry-1.docker.io/bitnamicharts"
