apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-web
  labels:
    {{- include "zuul.labels" . | nindent 4 }}
    app.kubernetes.io/component: zuul-web
    app.kubernetes.io/part-of: zuul
spec:
  replicas: {{ .Values.zuul.web.count }}
  selector:
    matchLabels:
      {{- include "zuul.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: zuul-web
      app.kubernetes.io/part-of: zuul
  template:
    metadata:
      labels:
        {{- include "zuul.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: zuul-web
        app.kubernetes.io/part-of: zuul
    spec:
      containers:
        - name: web
          image: {{ .Values.zuul.imagePrefix }}/zuul-web:{{ .Values.zuul.zuulImageVersion }}
          imagePullPolicy: Always
          env:
            - name: KUBECONFIG
              value: /etc/kubernetes/kube.config
          ports:
            - containerPort: 9000
              name: zuul-web
              protocol: TCP
          volumeMounts:
            - name: zuul-config
              mountPath: /etc/zuul
            - name: zookeeper-client-tls
              mountPath: /tls/client
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: zuul-config
          secret:
            secretName: zuul-config # pragma: allowlist secret
        - name: zookeeper-client-tls
          secret:
            secretName: {{ .Values.zuul.zookeeper.secretName }}
---
apiVersion: v1
kind: Service
metadata:
  name: zuul-web
  labels:
    {{- include "zuul.labels" . | nindent 4 }}
    app.kubernetes.io/component: zuul-web
    app.kubernetes.io/part-of: zuul
spec:
  type: NodePort
  selector:
    {{- include "zuul.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zuul-web
    app.kubernetes.io/part-of: zuul
  ports:
    - name: zuul-web
      port: 9000
      protocol: TCP
      targetPort: zuul-web
