---
apiVersion: v2
name: kubernetes-event-exporter
description: "Wrapper chart: Kubernetes Event Exporter"
type: application
version: 0.9.1
appVersion: "1.7.0"
dependencies:
  - name: nxs-universal-chart
    alias: nxs
    version: 3.2.1
    repository: "oci://registry.nixys.ru/nuc"
