# yamllint disable rule:line-length
---
nxs:
  releasePrefix: "-"

  generic:
    hookAnnotations: null
    usePredefinedAffinity: false

  serviceAccount:
    event-exporter:
      clusterRole:
        name: event-exporter
        rules:
          - apiGroups:
              - ""
            resources:
              - events
            verbs:
              - get
              - list
              - watch
          - apiGroups:
              - events.k8s.io
            resources:
              - events
            verbs:
              - get
              - list
              - watch

  configMaps:
    event-exporter-config:
      labels:
        app.kubernetes.io/component: event-exporter
      data:
        config.yaml: |-
          logLevel: warn
          logFormat: json
          metricsNamePrefix: event_exporter_
          route:
            routes:
              - drop:
                  - type: Normal
                  - reason: "Pulled|Pulling|Created|Started|Scheduled"
                match:
                  - receiver: ntfy
                    type: Warning
                    reason: FailedScheduling
                  - receiver: ntfy
                    type: Warning
                    reason: FailedMount
                  - receiver: ntfy
                    type: Warning
                    reason: FailedAttachVolume
                  - receiver: ntfy
                    type: Warning
                    reason: Failed
                  - receiver: ntfy
                    type: Warning
                    reason: BackOff
                  - receiver: ntfy
                    type: Warning
                    reason: Unhealthy
                  - receiver: ntfy
                    type: Warning
                    reason: ImagePullBackOff
                  - receiver: ntfy
                    type: Warning
                    reason: ErrImagePull
                  - receiver: ntfy
                    type: Warning
                    reason: CrashLoopBackOff
                  - receiver: ntfy
                    type: Warning
                    kind: Terraform
                    namespace: flux-system
                    reason: "ArtifactFailed|DependencyNotReady|DriftDetected"
                  - receiver: ntfy
                    type: Warning
                    kind: Terraform
                    namespace: flux-system
                    reason: "DriftDetectionFailed|HealthChecksFailed"
                  - receiver: ntfy
                    type: Warning
                    kind: Terraform
                    namespace: flux-system
                    reason: "OutputsWritingFailed|PostPlanningWebhookFailed"
                  - receiver: ntfy
                    type: Warning
                    kind: Terraform
                    namespace: flux-system
                    reason: "TFExecApplyFailed|TFExecInitFailed|TFExecNewFailed"
                  - receiver: ntfy
                    type: Warning
                    kind: Terraform
                    namespace: flux-system
                    reason: "TFExecOutputFailed|TFExecPlanFailed|ForceUnlock|LockHeld"
                  - receiver: ntfy
                    type: Warning
                    kind: Terraform
                    namespace: flux-system
                    reason: "TemplateGenerationFailed|VarsGenerationFailed"
                  - receiver: ntfy
                    type: Warning
                    kind: Terraform
                    namespace: flux-system
                    reason: "SelectWorkspaceFailed|DeletionBlockedByDependantsReason"
                  - receiver: ntfy
                    type: Warning
                    kind: Certificate
                  - receiver: ntfy
                    type: Warning
                    kind: CertificateRequest
                  - receiver: ntfy
                    type: Warning
                    kind: Order
                  - receiver: ntfy
                    type: Warning
                    kind: Challenge
                  - receiver: ntfy
                    type: Warning
                    kind: Issuer
                  - receiver: ntfy
                    type: Warning
                    kind: ClusterIssuer
          receivers:
            - name: ntfy
              webhook:
                endpoint: http://ntfy.ntfy.svc.cluster.local/prod-k8s-warnings
                headers:
                  Title: >-
                    Kubernetes {{`{{ "{{ .Reason }}" }}`}}:
                    {{`{{ "{{ .InvolvedObject.Kind }}" }}`}}/{{`{{ "{{ .InvolvedObject.Name }}" }}`}}
                  Priority: high
                  Tags: warning
                layout:
                  message: |-
                    warning: Kubernetes {{`{{ "{{ .Reason }}" }}`}}

                    Namespace: {{`{{ "{{ .InvolvedObject.Namespace }}" }}`}}
                    Kind: {{`{{ "{{ .InvolvedObject.Kind }}" }}`}}
                    Name: {{`{{ "{{ .InvolvedObject.Name }}" }}`}}
                    Source: {{`{{ "{{ .Source.Component }}" }}`}} {{`{{ "{{ .Source.Host }}" }}`}}
                    Count: {{`{{ "{{ .Count }}" }}`}}
                    Message: {{`{{ "{{ .Message }}" }}`}}
                  reason: "{{`{{ "{{ .Reason }}" }}`}}"
                  namespace: "{{`{{ "{{ .InvolvedObject.Namespace }}" }}`}}"
                  kind: "{{`{{ "{{ .InvolvedObject.Kind }}" }}`}}"
                  name: "{{`{{ "{{ .InvolvedObject.Name }}" }}`}}"
                  count: "{{`{{ "{{ .Count }}" }}`}}"

  deployments:
    event-exporter:
      replicas: 1
      automountServiceAccountToken: true
      serviceAccountName: event-exporter
      containers:
        event-exporter:
          image: docker.io/bitnamilegacy/kubernetes-event-exporter
          imageTag: 1.7.0-debian-12-r46
          imagePullPolicy: IfNotPresent
          args:
            - -conf=/data/config.yaml
          ports:
            - name: http
              containerPort: 2112
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: config
              mountPath: /data
              readOnly: true
      volumes:
        - name: config
          type: configMap
          originalName: event-exporter-config

  services:
    event-exporter:
      type: ClusterIP
      ports:
        - name: http
          port: 2112
          targetPort: http
          protocol: TCP
