---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kanboard
  namespace: flux-system
spec:
  releaseName: kanboard
  targetNamespace: kanboard
  storageNamespace: kanboard
  interval: 10m
  chart:
    spec:
      chart: ./production/kubernetes/helm-charts/kanboard-wrapper
      sourceRef:
        kind: GitRepository
        name: gerrit
        namespace: flux-system
