---
apiVersion: v2
name: envoy-gateway-wrapper
description: "Wrapper chart: Envoy Gateway"
type: application
version: 0.1.0
dependencies:
  - name: gateway-helm
    version: v1.7.3
    repository: "oci://docker.io/envoyproxy"
