---
apiVersion: v2
name: envoy-gateway-wrapper
description: "Wrapper chart: Envoy Gateway"
type: application
version: 0.8.0
dependencies:
  - name: gateway-helm
    version: 1.9.2
    repository: "oci://docker.io/envoyproxy"
