set shell := ["bash", "-euo", "pipefail", "-c"]

output_dir := "build"

# Show all available commands
default:
    @just --list --list-submodules

# Build the mock backpropagation presentation
backprop:
    mkdir -p "{{output_dir}}"
    latexmk -C -cd -outdir=../"{{output_dir}}" backprop/backprop.tex
    latexmk \
        -lualatex \
        -cd \
        -outdir=../"{{output_dir}}" \
        -interaction=nonstopmode \
        -halt-on-error \
        backprop/backprop.tex
    latexmk -c -cd -outdir=../"{{output_dir}}" backprop/backprop.tex
    rm -f \
        "{{output_dir}}/backprop.nav" \
        "{{output_dir}}/backprop.snm" \
        "{{output_dir}}/backprop.vrb"
    @echo "Presentation: presentations/{{output_dir}}/backprop.pdf"

# Build the reinforcement learning presentation
rl:
    mkdir -p "{{output_dir}}"
    latexmk \
        -lualatex \
        -cd \
        -outdir=../"{{output_dir}}" \
        -interaction=nonstopmode \
        -halt-on-error \
        rl/rl.tex
    latexmk -c -cd -outdir=../"{{output_dir}}" rl/rl.tex
    rm -f \
        "{{output_dir}}/rl.nav" \
        "{{output_dir}}/rl.snm" \
        "{{output_dir}}/rl.vrb"
    @echo "Presentation: presentations/{{output_dir}}/rl.pdf"
