---
apiVersion: v2
name: headlamp-wrapper
description: "Wrapper chart: headlamp"
type: application
version: 0.6.1
appVersion: "0.42.0"
dependencies:
  - name: headlamp
    version: 0.45.0
    repository: "https://kubernetes-sigs.github.io/headlamp/"
