---
apiVersion: v1
kind: Secret
metadata:
  name: zookeeper-secret
  namespace: zookeeper
type: Opaque
data:
  ca.crt: {{ .Values.caCrt }}
  tls.crt: {{ .Values.tlsCrt }}
  tls.key: {{ .Values.tlsKey }}
