{{- if .Values.certManager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-keystore-password
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.certManager.keystorePassword | required "certManager.keystorePassword is required" | b64enc | quote }}
{{- end }}
