---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-flux-template
  labels:
    app.kubernetes.io/name: ntfy
    app.kubernetes.io/component: templates
data:
  flux.yml: |
{{ .Files.Get "files/flux.yml" | indent 4 }}
