---
apiVersion: v2
name: redis-wrapper
description: "Wrapper chart: redis"
type: application
version: 0.35.0
dependencies:
  - name: redis
    version: 28.2.4
    repository: "oci://registry-1.docker.io/bitnamicharts"
