---
apiVersion: v2
name: redis-wrapper
description: "Wrapper chart: redis"
type: application
version: 0.9.0
dependencies:
  - name: redis
    version: 27.0.4
    repository: "oci://registry-1.docker.io/bitnamicharts"
