---
redis:
  global:
    defaultStorageClass: "local-rebuildable"
    storageClass: ""

  architecture: standalone

  auth:
    enabled: false

  master:
    resourcesPreset: "nano"
    persistence:
      enabled: true

  replica:
    resourcesPreset: "nano"
    persistence:
      enabled: true
