---
replicaCount: 1

image:
  repository: registry.your.domain/zuul-operator
  tag: "latest"

serviceAccount:
  create: true
  annotations: {}
  name: "zuul-operator"

podAnnotations: {}
podLabels: {}

installCRDs: true
