---
apiVersion: v2
name: zooreader
description: "Wrapper chart: zooreader"
type: application
version: 0.8.1
appVersion: "1.0.0"
dependencies:
  - name: nxs-universal-chart
    alias: nxs
    version: 3.1.0
    repository: "oci://registry.nixys.ru/nuc"
