---
apiVersion: v2
name: buildbuddy-wrapper
description: "Wrapper chart: buildbuddy"
type: application
version: 0.2.0
dependencies:
  - name: buildbuddy
    version: 0.0.397
    repository: "https://buildbuddy-io.github.io/buildbuddy-helm/"
