---
apiVersion: v2
name: buildbuddy-wrapper
description: "Wrapper chart: buildbuddy"
type: application
version: 0.11.0
dependencies:
  - name: buildbuddy
    version: 0.0.406
    repository: "https://buildbuddy-io.github.io/buildbuddy-helm/"
