---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: buildbuddy
  namespace: flux-system
spec:
  releaseName: buildbuddy
  targetNamespace: buildbuddy
  storageNamespace: buildbuddy
  interval: 10m
  chart:
    spec:
      chart: ./production/kubernetes/helm-charts/buildbuddy-wrapper
      sourceRef:
        kind: GitRepository
        name: gerrit
        namespace: flux-system
