---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: buildbuddy
  namespace: flux-system
spec:
  releaseName: buildbuddy
  targetNamespace: buildbuddy
  install:
    createNamespace: true
  storageNamespace: buildbuddy
  interval: 10m
  chart:
    spec:
      chart: ./production/kubernetes/helm-charts/buildbuddy-wrapper
      sourceRef:
        kind: GitRepository
        name: gerrit
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: production-output
      valuesKey: bb_access_key
      targetPath: buildbuddy.config.storage.aws_s3.static_credentials_id
      optional: false
    - kind: Secret
      name: production-output
      valuesKey: bb_secret_key
      targetPath: buildbuddy.config.storage.aws_s3.static_credentials_secret
      optional: false
