---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  install:
    createNamespace: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  releaseName: grafana
  targetNamespace: grafana
  storageNamespace: grafana
  interval: 10m
  chart:
    spec:
      chart: ./production/kubernetes/helm-charts/grafana-wrapper
      sourceRef:
        kind: GitRepository
        name: gerrit
        namespace: flux-system
  dependsOn:
    - name: authentik
    - name: local-path-provisioner
    - name: observability
